feat: support routes
Eomm/fastify-raw-body pull request #13
Opened 2021-08-27 10:10 UTC by kkorus

Hi, we could have an option to declare routes during plugin registration. That would help when using Fastify with NestJS where there is no option to set config on route like:

```
fastify.get('/en', { config: { rawBody: true } }, handler)
```

example usage: 

```
  app.register(rawBody2, {
    field: 'rawBody',
    global: false,
    encoding: false,
    runFirst: true,
    routes: ['/api/user/v1', 'api/contact/v1'],
  });
```

2021-09-01 10:57 UTC, Eomm requested changes
Could you add some unit tests?

2021-09-01 10:57 UTC, Eomm commented on package.json
> +  "version": "3.2.0",
Could you revert it?
It will be updated automatically on new releases

2021-09-16 20:22 UTC, phmz commented
Hello,
I'm also interested in this feature, is there anything I can do to help?
It would solve some of the issues we have with uploading files (fastify-multipart).

2021-09-17 07:20 UTC, Eomm commented
> I'm also interested in this feature, is there anything I can do to help? 

Would you like to push some tests to complete this PR?

2021-09-17 08:06 UTC, kkorus commented
Hi @Eomm, Yes, I will do this over the weekend.

2021-11-16 12:46 UTC, Tam2 commented
I'm interested in this change too, currently using global: true to work around this issue with nestjs

2021-11-16 12:53 UTC, Eomm commented
Would you like to push this feature over the line?

I'm more than happy to land it 👍🏼

2021-11-16 13:56 UTC, Tam2 commented
Raised #14 which includes test cases

2021-11-16 14:04 UTC, closed without merging